--Desde un usuario administrador Oracle como puede ser el user system

CREATE USER SOUTH_SUPERSTORE_NORMALIZED IDENTIFIED BY XXXXXX; --Introduce la contraseña deseada

grant create session  to SOUTH_SUPERSTORE_NORMALIZED;

grant connect to SOUTH_SUPERSTORE_NORMALIZED;

GRANT UNLIMITED TABLESPACE TO SOUTH_SUPERSTORE_NORMALIZED;

GRANT CREATE ANY TABLE TO SOUTH_SUPERSTORE_NORMALIZED;

GRANT CREATE ANY  SEQUENCE TO SOUTH_SUPERSTORE_NORMALIZED; --ANY?? DESDE USER system
GRANT CREATE ANY TRIGGER TO SOUTH_SUPERSTORE_NORMALIZED; --DESDE USER system