

-----------------------------------------------------------------------------CATEGORY--------------------------------------
	
	CREATE TABLE CATEGORY (
    ID_CATEGORY      	NUMBER(7),--AUTOINCREMENT
	CATEGORY			VARCHAR2(100 CHAR)
	);



ALTER TABLE CATEGORY ADD (
  CONSTRAINT PK_CATEGORY PRIMARY KEY (ID_CATEGORY));


CREATE SEQUENCE SEQ_CATEGORY START WITH 1;
	
CREATE OR REPLACE TRIGGER TRIGG_CATEGORY
BEFORE INSERT ON CATEGORY 
FOR EACH ROW

BEGIN
  SELECT SEQ_CATEGORY.NEXTVAL
  INTO   :new.ID_CATEGORY
  FROM   dual;
END;
