

-----------------------------------------------------------------------------SUBCATEGORY--------------------------------------
	
	CREATE TABLE SUBCATEGORY (
    ID_SUBCATEGORY      NUMBER(7),--AUTOINCREMENT
	SUBCATEGORY			VARCHAR2(100 CHAR),
	CATEGORY_ID			NUMBER(7)
	);



ALTER TABLE SUBCATEGORY ADD (
  CONSTRAINT PK_SUBCATEGORY PRIMARY KEY (ID_SUBCATEGORY));


CREATE SEQUENCE SEQ_SUBCATEGORY START WITH 1;
	
CREATE OR REPLACE TRIGGER TRIGG_SUBCATEGORY
BEFORE INSERT ON SUBCATEGORY 
FOR EACH ROW

BEGIN
  SELECT SEQ_SUBCATEGORY.NEXTVAL
  INTO   :new.ID_SUBCATEGORY
  FROM   dual;
END;

ALTER TABLE SUBCATEGORY ADD CONSTRAINT FK_CATEGORY FOREIGN KEY
 ( CATEGORY_ID ) 
 REFERENCES CATEGORY ( ID_CATEGORY ) 
ALTER TABLE SUBCATEGORY MODIFY CONSTRAINT FK_CATEGORY RELY ;
