


-----------------------------------------------------------------------------TARGET--------------------------------------
	
	CREATE TABLE TARGET (
    ID_SUBCATEGORY NUMBER(7) NOT NULL,--AUTOINCREMENT
	YEAR			NUMBER(4) NOT NULL,
	PROFIT_TARGET	NUMBER(38,25),
	SALES_TARGET	NUMBER(38,25)
	);



ALTER TABLE TARGET ADD (
  CONSTRAINT PK_TARGET PRIMARY KEY (ID_SUBCATEGORY,YEAR));




ALTER TABLE TARGET ADD CONSTRAINT FK_SUBCATEGORY_TARGET FOREIGN KEY
 ( ID_SUBCATEGORY ) 
 REFERENCES SUBCATEGORY ( ID_SUBCATEGORY ) ;
ALTER TABLE TARGET MODIFY CONSTRAINT FK_SUBCATEGORY_TARGET RELY ;

