

-----------------------------------------------------------------------------CUSTOMER--------------------------------------
	
	CREATE TABLE CUSTOMER (
    ID_CUSTOMER      	NUMBER(7),--AUTOINCREMENT
	CUSTOMER			VARCHAR2(50 CHAR),
	CUSTOMER_NAME		VARCHAR2(200 CHAR),
    SEGMENT             VARCHAR2(50 CHAR),
	FLAG_REWARD			NUMBER(1)
	);



ALTER TABLE CUSTOMER ADD (
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID_CUSTOMER));



CREATE SEQUENCE SEQ_CUSTOMER START WITH 1;
	

CREATE OR REPLACE TRIGGER TRIGG_CUSTOMER
BEFORE INSERT ON CUSTOMER 
FOR EACH ROW

BEGIN
  SELECT SEQ_CUSTOMER.NEXTVAL
  INTO   :new.ID_CUSTOMER
  FROM   dual;
END;


