

	
	CREATE TABLE TARGET (
    PRODUCT_SUBCATEGORY VARCHAR(100 CHAR) NOT NULL,
	ORDER_YEAR			NUMBER(4) NOT NULL,
	PROFIT_TARGET	NUMBER(38,25),
	SALES_TARGET	NUMBER(38,25)
	);



ALTER TABLE TARGET ADD (
  CONSTRAINT PK_TARGET PRIMARY KEY (PRODUCT_SUBCATEGORY,ORDER_YEAR));
