

-----------------------------------------------------------------------------PRODUCT--------------------------------------
	
	CREATE TABLE PRODUCT (
    ID_PRODUCT      	NUMBER(7),--AUTOINCREMENT
	PRODUCT				VARCHAR2(100 CHAR),
	PRODUCT_NAME		VARCHAR2(400 CHAR),
	SUBCATEGORY_ID			NUMBER(7)
	);



ALTER TABLE PRODUCT ADD (
  CONSTRAINT PK_PRODUCT PRIMARY KEY (ID_PRODUCT));



ALTER TABLE PRODUCT ADD CONSTRAINT FK_SUBCATEGORY FOREIGN KEY
 ( SUBCATEGORY_ID ) 
 REFERENCES SUBCATEGORY ( ID_SUBCATEGORY ) 
ALTER TABLE PRODUCT MODIFY CONSTRAINT FK_SUBCATEGORY RELY ;

CREATE SEQUENCE SEQ_PRODUCT START WITH 1;
	

CREATE OR REPLACE TRIGGER TRIGG_PRODUCT
BEFORE INSERT ON PRODUCT 
FOR EACH ROW

BEGIN
  SELECT SEQ_PRODUCT.NEXTVAL
  INTO   :new.ID_PRODUCT
  FROM   dual;
END;



