CREATE TABLE SOUTH_SUPERSTORE.ORDERS (
    ID_ROW              NUMBER(10),
    ID_ORDER      		VARCHAR2(20 CHAR),
    ORDER_DATE       	DATE,
    SHIP_DATE       	DATE,
    SHIP_MODE          	VARCHAR2(100 CHAR),
	CUSTOMER_ID			NUMBER(7),
	PRODUCT_ID			NUMBER(7),
	LOCATION_ID			NUMBER(7),
    SALES          		NUMBER(38,25),
	QUANTITY			NUMBER(9),
	DISCOUNT			NUMBER(3,2),
	PROFIT				NUMBER(38,25), 
	ORDER_YEAR			NUMBER(4),
	FLAG_RETURNED		NUMBER(1)
	
	);
	
	CREATE UNIQUE INDEX SOUTH_SUPERSTORE.PK_ORDERS ON SOUTH_SUPERSTORE.ORDERS
  (
    ID_ROW ASC ,ID_ORDER ASC
  );

ALTER TABLE SOUTH_SUPERSTORE.ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY ( ID_ROW,ID_ORDER );
ALTER TABLE SOUTH_SUPERSTORE.ORDERS MODIFY CONSTRAINT PK_ORDERS RELY ;

ALTER TABLE SOUTH_SUPERSTORE.ORDERS ADD CONSTRAINT FK_LOCATION FOREIGN KEY
 ( LOCATION_ID ) 
 REFERENCES SOUTH_SUPERSTORE.LOCATION ( ID_LOCATION ) 
 ENABLE VALIDATE;
ALTER TABLE SOUTH_SUPERSTORE.ORDERS MODIFY CONSTRAINT FK_LOCATION RELY ;

ALTER TABLE SOUTH_SUPERSTORE.ORDERS ADD CONSTRAINT FK_PRODUCT FOREIGN KEY
 ( PRODUCT_ID ) 
 REFERENCES SOUTH_SUPERSTORE.PRODUCT( ID_PRODUCT ) 
 ENABLE VALIDATE ;
ALTER TABLE SOUTH_SUPERSTORE.ORDERS MODIFY CONSTRAINT FK_PRODUCT RELY ;


ALTER TABLE SOUTH_SUPERSTORE.ORDERS ADD CONSTRAINT FK_CUSTOMER FOREIGN KEY
 ( CUSTOMER_ID ) 
 REFERENCES SOUTH_SUPERSTORE.CUSTOMER ( ID_CUSTOMER ) 
ENABLE VALIDATE;
ALTER TABLE SOUTH_SUPERSTORE.ORDERS MODIFY CONSTRAINT FK_CUSTOMER RELY ;

