--------------------------------------------------------
-- Archivo creado  - viernes-agosto-21-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "SOUTH_SUPERSTORE"."CATEGORY" 
   (	"ID_CATEGORY" NUMBER(7,0), 
	"CATEGORY" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SOUTH_SUPERSTORE.CATEGORY
SET DEFINE OFF;
Insert into SOUTH_SUPERSTORE.CATEGORY (ID_CATEGORY,CATEGORY) values ('1621','Office Supplies');
Insert into SOUTH_SUPERSTORE.CATEGORY (ID_CATEGORY,CATEGORY) values ('1622','Technology');
Insert into SOUTH_SUPERSTORE.CATEGORY (ID_CATEGORY,CATEGORY) values ('1623','Furniture');
commit;
--------------------------------------------------------
--  DDL for Index PK_CATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUTH_SUPERSTORE"."PK_CATEGORY" ON "SOUTH_SUPERSTORE"."CATEGORY" ("ID_CATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGG_CATEGORY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SOUTH_SUPERSTORE"."TRIGG_CATEGORY" 
BEFORE INSERT ON CATEGORY 
FOR EACH ROW

BEGIN
  SELECT SEQ_CATEGORY.NEXTVAL
  INTO   :new.ID_CATEGORY
  FROM   dual;
END;
/
ALTER TRIGGER "SOUTH_SUPERSTORE"."TRIGG_CATEGORY" ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "SOUTH_SUPERSTORE"."CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("ID_CATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
