--------------------------------------------------------
-- Archivo creado  - viernes-agosto-21-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SUBCATEGORY
--------------------------------------------------------

  CREATE TABLE "SOUTH_SUPERSTORE"."SUBCATEGORY" 
   (	"ID_SUBCATEGORY" NUMBER(7,0), 
	"SUBCATEGORY" VARCHAR2(100 CHAR), 
	"CATEGORY_ID" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SOUTH_SUPERSTORE.SUBCATEGORY
SET DEFINE OFF;
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3278','Appliances','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3279','Copiers','1622');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3280','Machines','1622');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3281','Supplies','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3282','Bookcases','1623');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3283','Art','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3284','Chairs','1623');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3285','Binders','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3286','Phones','1622');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3287','Fasteners','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3288','Paper','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3289','Labels','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3290','Furnishings','1623');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3291','Envelopes','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3292','Accessories','1622');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3293','Storage','1621');
Insert into SOUTH_SUPERSTORE.SUBCATEGORY (ID_SUBCATEGORY,SUBCATEGORY,CATEGORY_ID) values ('3294','Tables','1623');
--------------------------------------------------------
--  DDL for Index PK_SUBCATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUTH_SUPERSTORE"."PK_SUBCATEGORY" ON "SOUTH_SUPERSTORE"."SUBCATEGORY" ("ID_SUBCATEGORY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIGG_SUBCATEGORY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "SOUTH_SUPERSTORE"."TRIGG_SUBCATEGORY" 
BEFORE INSERT ON SUBCATEGORY 
FOR EACH ROW

BEGIN
  SELECT SEQ_SUBCATEGORY.NEXTVAL
  INTO   :new.ID_SUBCATEGORY
  FROM   dual;
END;
/
ALTER TRIGGER "SOUTH_SUPERSTORE"."TRIGG_SUBCATEGORY" ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "SOUTH_SUPERSTORE"."SUBCATEGORY" ADD CONSTRAINT "PK_SUBCATEGORY" PRIMARY KEY ("ID_SUBCATEGORY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBCATEGORY
--------------------------------------------------------

  ALTER TABLE "SOUTH_SUPERSTORE"."SUBCATEGORY" ADD CONSTRAINT "FK_CATEGORY" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "SOUTH_SUPERSTORE"."CATEGORY" ("ID_CATEGORY") DEFERRABLE RELY DISABLE;
