
	
	CREATE TABLE REWARD_CUSTOMER (
	ID_CUSTOMER			VARCHAR2(50 CHAR),
	CUSTOMER_NAME		VARCHAR2(200 CHAR)
	);



ALTER TABLE REWARD_CUSTOMER ADD (
  CONSTRAINT PK_REWARD_CUSTOMER PRIMARY KEY (ID_CUSTOMER));
  
