--------------------------------------------------------
-- Archivo creado  - viernes-agosto-21-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDER_RETURN
--------------------------------------------------------

  CREATE TABLE "SOUTH_SUPERSTORE_ORIGINAL"."ORDER_RETURN" 
   (	"ID_ORDER" VARCHAR2(20 CHAR), 
	"STATUS" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN
SET DEFINE OFF;
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2011-106054','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2011-167199','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2011-149020','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2011-162775','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2011-109232','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2011-103366','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-154921','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-109708','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2012-113327','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-163923','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-136224','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-162201','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-110947','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-101868','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2012-123960','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-121720','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-104115','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-104941','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-137281','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2012-106495','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-147011','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-156734','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-133242','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-123330','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2012-106187','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-155439','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-162159','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-134208','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-140928','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-145905','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-111409','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-142370','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-134516','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-157280','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2013-153815','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-152156','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-137736','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-131968','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-121958','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-131065','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2013-130820','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2013-138408','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-162033','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-113705','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2014-166611','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-129910','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2014-159205','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-133263','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-134495','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-129028','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-161053','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-161970','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-121314','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-102309','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-144694','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-163335','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-134096','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2014-132675','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-116939','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-129490','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-160017','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-118402','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('US-2014-162558','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-116113','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-149853','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-148404','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-162635','Returned');
Insert into SOUTH_SUPERSTORE_ORIGINAL.ORDER_RETURN (ID_ORDER,STATUS) values ('CA-2014-149146','Returned');
commit;
--------------------------------------------------------
--  DDL for Index PK_ORDER_RETURN
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUTH_SUPERSTORE_ORIGINAL"."PK_ORDER_RETURN" ON "SOUTH_SUPERSTORE_ORIGINAL"."ORDER_RETURN" ("ID_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ORDER_RETURN
--------------------------------------------------------

  ALTER TABLE "SOUTH_SUPERSTORE_ORIGINAL"."ORDER_RETURN" ADD CONSTRAINT "PK_ORDER_RETURN" PRIMARY KEY ("ID_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
