--------------------------------------------------------
-- Archivo creado  - viernes-agosto-21-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table REWARD_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SOUTH_SUPERSTORE_ORIGINAL"."REWARD_CUSTOMER" 
   (	"ID_CUSTOMER" VARCHAR2(50 CHAR), 
	"CUSTOMER_NAME" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER
SET DEFINE OFF;
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JO-15145','Jack O''Briant');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('ME-17320','Maria Etezadi');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AJ-10780','Anthony Jacobs');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CS-12250','Chris Selesnick');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('ND-18370','Natalie DeCherney');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EH-13990','Erica Hackney');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('HL-15040','Hunter Lopez');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MM-18280','Muhammed MacIntyre');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TB-21400','Tom Boeckenhauer');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SD-20485','Shirley Daniels');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EB-13930','Eric Barreto');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('ND-18460','Neil Ducich');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NF-18385','Natalie Fritzler');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AJ-10945','Ashley Jarboe');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CL-12565','Clay Ludtke');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SC-20095','Sanjit Chand');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('FM-14215','Filia McAdams');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CK-12325','Christine Kargatis');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NF-18475','Neil Französisch');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AS-10240','Alan Shonely');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KN-16705','Kristina Nunn');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MH-17440','Mark Haberlin');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SM-20320','Sean Miller');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MC-17605','Matt Connell');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TS-21205','Thomas Seio');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KH-16690','Kristen Hastings');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GM-14440','Gary McGarr');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CC-12685','Craig Carroll');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BG-11740','Bruce Geld');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KB-16240','Karen Bern');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TG-21640','Trudy Glocke');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RD-19585','Rob Dowd');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AH-10690','Anna Häberlin');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KB-16585','Ken Black');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GM-14695','Greg Maxwell');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RP-19855','Roy Phan');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PJ-19015','Pauline Johnson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RS-19765','Roland Schwarz');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('VM-21685','Valerie Mitchum');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RA-19885','Ruben Ausman');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JK-15370','Jay Kimmel');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SP-20650','Stephanie Phelps');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AG-10390','Allen Goldenen');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DB-13555','Dorothy Badders');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('LC-16885','Lena Creighton');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('HG-14845','Harry Greene');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('LA-16780','Laura Armstrong');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TM-21010','Tamara Manning');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JM-16195','Justin MacKendrick');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CS-11860','Cari Schnelling');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PF-19120','Peter Fuller');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GD-14590','Giulietta Dortch');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SB-20290','Sean Braxton');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EH-14005','Erica Hernandez');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AJ-10795','Anthony Johnson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TD-20995','Tamara Dahlen');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MW-18235','Mitch Willingham');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EH-14185','Evan Henry');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EB-13840','Ellis Ballard');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JK-15625','Jim Karlsson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('LT-17110','Liz Thompson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KC-16255','Karen Carlisle');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TT-21070','Ted Trevino');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DL-12925','Daniel Lacy');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DA-13450','Dianna Arnett');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BN-11470','Brad Norvell');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EA-14035','Erin Ashbrook');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CA-12775','Cynthia Arntzen');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JC-15775','John Castell');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KT-16465','Kean Takahito');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JL-15835','John Lee');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MS-17365','Maribeth Schnelling');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KD-16495','Keith Dawkins');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('XP-21865','Xylona Preis');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BW-11200','Ben Wallace');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KW-16570','Kelly Williams');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SL-20155','Sara Luxemburg');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JG-15115','Jack Garza');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BP-11095','Bart Pistole');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MA-17995','Michelle Arnett');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DL-12865','Dan Lawera');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AS-10225','Alan Schoenberger');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('LS-17200','Luke Schmidt');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('FH-14365','Fred Hopkins');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('FH-14275','Frank Hawley');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NB-18580','Nicole Brennan');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DB-12910','Daniel Byrd');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AP-10915','Arthur Prichep');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RD-19810','Ross DeVincentis');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KH-16630','Ken Heidel');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JK-16120','Julie Kriz');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AT-10735','Annie Thurman');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SH-20395','Shahid Hopkins');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('ON-18715','Odella Nelson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SR-20740','Steven Roelle');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BG-11035','Barry Gonzalez');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GA-14515','George Ashbrook');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DM-13345','Denise Monton');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CC-12220','Chris Cortes');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JF-15190','Jamie Frazer');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RM-19675','Robert Marley');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DH-13075','Dave Hallsten');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RB-19645','Robert Barroso');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('HP-14815','Harold Pawlan');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BF-11080','Bart Folk');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RF-19345','Randy Ferguson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TB-21280','Toby Braunhardt');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EM-13825','Elizabeth Moffitt');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EB-13870','Emily Burns');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MP-17965','Michael Paige');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SS-20515','Shirley Schmidt');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('YS-21880','Yana Sorensen');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PG-18820','Patrick Gardner');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AR-10405','Allen Rosenblatt');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EM-14095','Eudokia Martin');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BW-11065','Barry Weirich');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CK-12595','Clytie Kelty');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GK-14620','Grace Kelly');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('HG-14965','Henry Goldwyn');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('FH-14350','Fred Harton');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('KW-16435','Katrina Willman');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JC-16105','Julie Creighton');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TW-21025','Tamara Willingham');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CK-12760','Cyma Kinney');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AT-10435','Alyssa Tate');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SW-20455','Shaun Weien');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('VW-21775','Victoria Wilson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AM-10705','Anne McFarland');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NG-18355','Nat Gilpin');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NW-18400','Natalie Webber');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BD-11500','Bradley Drucker');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DB-13405','Denny Blanton');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JR-16210','Justin Ritter');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TC-21535','Tracy Collins');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NH-18610','Nicole Hansen');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GB-14575','Giulietta Baptist');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MG-17875','Michael Grace');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SJ-20125','Sanjit Jacobs');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MC-17275','Marc Crier');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('ML-17395','Marina Lichtenstein');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JK-15205','Jamie Kunitz');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NP-18685','Nora Pelletier');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DJ-13420','Denny Joy');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JJ-15760','Joel Jenkins');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DK-13090','Dave Kipp');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SC-20575','Sonia Cooley');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JD-15790','John Dryer');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SO-20335','Sean O''Donnell');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AF-10885','Art Foster');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GM-14500','Gene McClure');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RA-19285','Ralph Arnett');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TT-21220','Thomas Thornton');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MS-17530','MaryBeth Skach');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EG-13900','Emily Grady');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GB-14530','George Bell');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CP-12340','Christine Phan');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RH-19600','Rob Haberlin');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NS-18640','Noel Staavos');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JK-15730','Joe Kamberova');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AA-10375','Allen Armold');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('FM-14380','Fred McMath');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PJ-18835','Patrick Jones');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SS-20875','Sung Shariari');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JH-15820','John Huston');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BH-11710','Brosina Hoffman');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SF-20065','Sandra Flanagan');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SH-20635','Stefanie Holloman');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DO-13435','Denny Ordway');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TB-21190','Thomas Brumley');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('HJ-14875','Heather Jas');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MC-17425','Mark Cousins');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PA-19060','Pete Armstrong');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MV-18190','Mike Vittorini');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PM-18940','Paul MacIntyre');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EC-14050','Erin Creighton');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TC-21475','Tony Chapman');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AH-10195','Alan Haines');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SC-20800','Stuart Calhoun');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AB-10255','Alejandro Ballentine');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('LC-17140','Logan Currie');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TS-21655','Trudy Schmidt');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JW-15955','Joni Wasserman');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MH-17290','Marc Harrigan');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TS-21085','Thais Sissman');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('RB-19570','Rob Beeghly');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CA-11965','Carol Adams');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SC-20380','Shahid Collister');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MV-17485','Mark Van Huff');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SW-20245','Scot Wooten');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('LP-17095','Liz Preis');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CB-12535','Claudia Bergmann');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('VB-21745','Victoria Brennan');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GA-14725','Guy Armstrong');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PW-19030','Pauline Webber');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('LC-16870','Lena Cacioppo');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BF-11020','Barry Französisch');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CS-12400','Christopher Schild');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('HR-14770','Hallie Redmond');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MG-18205','Mitch Gastineau');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('HM-14980','Henry MacAllister');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AA-10480','Andrew Allen');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JL-15130','Jack Lebron');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JL-15235','Janet Lee');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SS-20140','Saphhira Shifley');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MH-18115','Mick Hernandez');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('CJ-12010','Caroline Jumper');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AG-10900','Arthur Gainer');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('GZ-14470','Gary Zandusky');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MB-18085','Mick Brown');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EJ-14155','Eva Jacobs');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('TB-21355','Todd Boyes');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AH-10075','Adam Hart');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DW-13480','Dianna Wilson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('EH-13945','Eric Hoffmann');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BW-11110','Bart Watters');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PO-18865','Patrick O''Donnell');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('NR-18550','Nick Radford');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('LW-16990','Lindsay Williams');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('PG-18895','Paul Gonzalez');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DR-12880','Dan Reichenbach');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('DV-13045','Darrin Van Huff');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('HZ-14950','Henia Zydlo');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BS-11590','Brendan Sweed');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SW-20275','Scott Williamson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AS-10090','Adam Shillingsburg');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MC-17575','Matt Collins');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BT-11680','Brian Thompson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('JE-16165','Justin Ellison');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AI-10855','Arianne Irving');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('AG-10330','Alex Grayson');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('BD-11635','Brian Derr');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('SR-20425','Sharelle Roach');
Insert into SOUTH_SUPERSTORE_ORIGINAL.REWARD_CUSTOMER (ID_CUSTOMER,CUSTOMER_NAME) values ('MF-18250','Monica Federle');
--------------------------------------------------------
--  DDL for Index PK_REWARD_CUSTOMER
--------------------------------------------------------

  CREATE UNIQUE INDEX "SOUTH_SUPERSTORE_ORIGINAL"."PK_REWARD_CUSTOMER" ON "SOUTH_SUPERSTORE_ORIGINAL"."REWARD_CUSTOMER" ("ID_CUSTOMER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table REWARD_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SOUTH_SUPERSTORE_ORIGINAL"."REWARD_CUSTOMER" ADD CONSTRAINT "PK_REWARD_CUSTOMER" PRIMARY KEY ("ID_CUSTOMER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
